config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :products
  root 'products#index'
  resource :cart, only: [:show] do
  	post "add",path: "add/:id", on: :member	
  	get :checkout
  end
  resources :orders, only: [:index,:create,:show,:update] do
  	member do 
  		get :new_payment
  		post :pay
  	end
  end

  end

app/views/partials/_cart.html.haml
-if @cart
	%p.navbar-text.navbar-right
		-if @cart.empty?
			Cart is empty.
		-else
			=link_to "You have #{pluralize @cart.items.length,"item"}",cart_path

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">STORE.ME</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Products", products_path %></li>
        <li class="dropdown">
          <%= link_to "#",data: {toggle: "dropdown"} do %>
            Categories
            <span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu">
          <% @categories.each do |category| %>
            <li><%= link_to category.name, category %></li>
          <% end %>
          </ul>
        </li>
      </ul>

      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
          Logged in as <%= current_user.name %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "navbar-link" %><br />
        <% end %>

      </p>
      <%= render 'partials/cart' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>