config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :products
  root 'products#index'
  resource :cart, only: [:show] do
  	post "add",path: "add/:id", on: :member	
  	get :checkout
  end
  resources :orders, only: [:index,:create,:show,:update] do
  	member do 
  		get :new_payment
  		post :pay
  	end
  end

  end

app/models/cart.rb
class Cart
	attr_reader :items

	def self.builds_from_hash hash
		items = if hash["cart"] then 
			hash["cart"]["items"].map do |item_data|
			CartItem.new item_data["product_id"], item_data["quantity"]
		end
	else
		[]
	end
		new items
	end


	def initialize items = []
		@items = items
	end

	def add_item product_id	
		item = @items.find {|item| item.product_id == product_id }
		if item
			item.increment
		else
			@items << CartItem.new(product_id)
		end
	end

	def empty?
		@items.empty?
	end

	def serialize
		items = @items.map {|item| {"product_id" => item.product_id,"quantity" => item.quantity}}
		{
				"items" => items
		}
	end

	def total_price
		@items.inject(0) {|sum,item|  sum+item.total_price}
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_filter :initialize_cart

	def add
		@cart.add_item params[:id]
		session["cart"] = @cart.serialize
		product = Product.find(params[:id])
		redirect_to :back, notice: "Added #{product.name} to cart"
	end
	def show
		
	end

	def checkout
		@order_form = OrderForm.new user: User.new
		@client_token = Braintree::ClientToken.generate
	end
end

app/views/carts/checkout.html.haml
%h1 Checkout
%h2 You have the following items in your cart.
%ul
	-@cart.items.each do |item|
		%li
			%en=item.quantity 
			=item.product.name
			=item.total_price
%p
	%strong
		Total Price:
		=number_to_currency @cart.total_price

=form_for @order_form,url: orders_path do |f|
	=render "orders/errors"
	%h3 Some of your personal details
	=f.fields_for :user, f.object.user do |u|
		.form-group
			%p=u.text_field :name,placeholder: "Name", class: "form-control input-lg"
			%p
				=u.text_field :email, placeholder: "Email",class: "form-control"
				%span.help-block This will help you track your order more effectively
		.form-group
			.row
				%p.col-md-6=u.text_field :address, placeholder: "Address",class: "form-control"
				%p.col-md-3=u.text_field :postal_code,placeholder: "Postal Code / Zipcode", class: "form-control"
				%p.col-md-3=u.text_field :city, placeholder: "City",class: "form-control"
			%p=u.country_select :country, {priority_countries: ["GB","US","DE","ES","PT"]}, {class: "form-control"}
			%p=u.text_field :phone, class: "form-control", placeholder: "Phone"

		#payment-form

		%p=f.submit "Place Order",class: "btn btn-primary"

:javascript
	var clientToken = "#{@client_token}";

	braintree.setup(clientToken, "dropin", {
		container: "payment-form"
	});

app/views/carts/show.html.haml
%table.table.table-hover
	%thead
		%tr
			%th Quantity
			%th Name
			%th Total
	-@cart.items.each do |item|
		%tr
			%td= item.quantity
			%td
				=image_tag item.product.image.thumb
				=link_to item.product.name, item.product
			%td= item.total_price

%p= @cart.total_price

%p= link_to "Checkout", checkout_cart_path, class:"btn btn-primary"