config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :users
  resources :products
  root 'products#index'
  resource :cart, only: [:show] do
  	post "add",path: "add/:id", on: :member	
  	get :checkout
  end
  resources :orders, only: [:index,:create,:show,:update] do
  	member do 
  		get :new_payment
  		post :pay
  	end
  end

  end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.includes(:products).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%h1
  = @category.name
  =render "products/table", products: @products